        COPY INTO SNOWFLAKE_LEARNING_DB.PUBLIC.ALLOCATION
  FROM @SNOWAZURESTAGE
FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    DATE_FORMAT = 'DD/MM/YYYY'
)
