-- Raw staging table to land JSON as-is from Blob
CREATE OR REPLACE TABLE SNOWFLAKE_LEARNING_DB.TWITCH.TWITCH_TOP_GAMES_RAW (
    RAW_JSON        VARIANT,
    LOADED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE     VARCHAR(500),
    PIPELINE_RUN_ID VARCHAR(100)
);

CREATE OR REPLACE TABLE SNOWFLAKE_LEARNING_DB.TWITCH.TWITCH_TOP_GAMES (
    GAME_ID             VARCHAR(20)     NOT NULL,
    GAME_NAME           VARCHAR(500)    NOT NULL,
    BOX_ART_URL         VARCHAR(1000),
    IGDB_ID             VARCHAR(20),
    PAGINATION_CURSOR   VARCHAR(500),
    HAS_IGDB_MAPPING    BOOLEAN         GENERATED ALWAYS AS (IGDB_ID IS NOT NULL AND IGDB_ID != ''),
    LOADED_AT           TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    PIPELINE_RUN_ID     VARCHAR(100),
    SOURCE_FILE         VARCHAR(500),
    CONSTRAINT PK_TWITCH_TOP_GAMES PRIMARY KEY (GAME_ID)
);
