COPY INTO SNOWFLAKE_LEARNING_DB.TWITCH.TWITCH_TOP_GAMES_RAW (
    RAW_JSON,
    SOURCE_FILE,
    LOADED_AT
)
FROM (
    SELECT
        $1,
        METADATA$FILENAME,
        CURRENT_TIMESTAMP()
    FROM @SNOWFLAKE_LEARNING_DB.PUBLIC.SNOWAZURETWITCHSTAGE/games/top/2026/05/04/
)
PATTERN             = '.*\\.json$'
ON_ERROR            = 'CONTINUE'
PURGE               = FALSE;
